name: ContanarizedBuildACR

on: workflow_dispatch

permissions:             # OpenID Connect (OIDC) authentication. requireds read write permission:
  id-token: write        # other wise gives error: Failed to fetch federated token from GitHub. Please make sure to give write permissions to id-token in the workflow
  contents: read

jobs:
  Docker_Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4         

    # Login to Azure using OIDC for authentication
    - name: Azure CLI login
      uses: azure/login@v2
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Azure ACR login
      run: az acr login --name registryforcimages   #  ACR name

    - name: Docker Build 
      run: |
        docker build -t java-sum:javaimage .   

    - name: Tag image for ACR
      run: |
         docker tag java-sum:javaimage \
         registryforcimages.azurecr.io/git-action-images:javaimage

    - name: Push to Azure Container Registry
      run: |
        docker push registryforcimages.azurecr.io/git-action-images:javaimage
